CREATE DATABASE DB_CONTRATO_EVENTOS

USE DB_CONTRATO_EVENTOS

CREATE TABLE TB_CONTRATANTE (
CNPJ VARCHAR(14) CONSTRAINT CONST_PK_CONTRATANTE PRIMARY KEY,
NOME VARCHAR(100),
CEP INT,
TELEFONE INT,
)

CREATE TABLE TB_CONTRATADO (
MATRICULA INT IDENTITY CONSTRAINT CONST_PK_CONTRATADO PRIMARY KEY,
NOME VARCHAR(100)
)

CREATE TABLE TB_CONTRATO (
NUMERO INT IDENTITY CONSTRAINT CONST_PK_CONTRATO PRIMARY KEY,
DATA_CONTRATO DATE,
DURACAO_HORA INT,
VALOR MONEY,
FK_CONTRATANTE VARCHAR(14) CONSTRAINT CONST_FK_CONTRATANTE FOREIGN KEY REFERENCES TB_CONTRATANTE(CNPJ)
)

CREATE TABLE TB_FUNCAO (
CODIGO INT IDENTITY CONSTRAINT CONST_PK_FUNCAO PRIMARY KEY,
NOME VARCHAR(50)
)

CREATE TABLE TB_FUNCAO_CONTRATADO(
CODIGO INT IDENTITY CONSTRAINT CONST_PK_FUNC_CONTRATADO PRIMARY KEY,
NOME VARCHAR(100),
FK_FUNCAO_FUNCCONT INT CONSTRAINT FK_FUNCAO_FUNCCONT FOREIGN KEY REFERENCES TB_FUNCAO(CODIGO),
FK_CONTRATADO_FUNCCONT INT CONSTRAINT FK_CONTRATADO_FUNCCONT FOREIGN KEY REFERENCES TB_CONTRATADO(MATRICULA)
)