CREATE DATABASE DB_DEPARTAMENTO

USE DB_DEPARTAMENTO

CREATE TABLE TB_PROFISSAO(
CODIGO INT IDENTITY CONSTRAINT CONST_PROFISSAO_PK PRIMARY KEY,
DESCRICAO VARCHAR(100)
)

CREATE TABLE TB_DEPARTAMENTO(
SIGLA VARCHAR(4) CONSTRAINT CONST_DEPTO_PK PRIMARY KEY,
NOME VARCHAR(100)
)

CREATE TABLE TB_FUNCIONARIO(
MATRICULA INT IDENTITY CONSTRAINT CONST_FUNC_PK PRIMARY KEY,
NOME VARCHAR(100),
SALARIO MONEY,
FK_PROFISSAO INT CONSTRAINT CONST_PROF_FK FOREIGN KEY REFERENCES TB_PROFISSAO(CODIGO),
FK_DEPARTAMENTO VARCHAR(4) CONSTRAINT CONST_DPTO_FK FOREIGN KEY REFERENCES TB_DEPARTAMENTO(SIGLA)
)

CREATE TABLE TB_UNID_FED (
SIGLA VARCHAR(3) CONSTRAINT CONST_UNIDFED_PK PRIMARY KEY,
NOME VARCHAR(50)
)

CREATE TABLE TB_FILIAL(
CODIGO INT IDENTITY CONSTRAINT CONST_FILIAL_PK PRIMARY KEY,
CIDADE VARCHAR(50),
CEP INT,
FK_UNID_FED VARCHAR(3) CONSTRAINT CONST_UNIDFED_FK FOREIGN KEY REFERENCES TB_UNID_FED(SIGLA)
)

CREATE TABLE TB_DEPTO_FILIAL(
CODIGO INT IDENTITY CONSTRAINT CONST_DPTOFILIAL_PK PRIMARY KEY,
FK_DPTO_DPTOFILIAL VARCHAR(4) CONSTRAINT CONST_DPTO_DPTOFILIAL_FK FOREIGN KEY REFERENCES TB_DEPARTAMENTO(SIGLA),
FK_FILIAL_DPTOFILIAL INT CONSTRAINT CONST_FILIAL_DPTOFILIAL_FK FOREIGN KEY REFERENCES TB_FILIAL(CODIGO)
)