CREATE DATABASE DB_EVENTO_MUSICAL

USE DB_EVENTO_MUSICAL

CREATE TABLE TB_LOCAL(
CODIGO INT IDENTITY CONSTRAINT CONST_LOCAL_PK PRIMARY KEY,
NOME VARCHAR(100),
CIDADE VARCHAR(60),
ESTADO VARCHAR(30),
BAIRRO VARCHAR(50),
RUA VARCHAR(50),
NUMERO INT, 
CEP INT
)

CREATE TABLE TB_ORGANIZADOR(
MATRICULA INT IDENTITY CONSTRAINT CONST_ORGANIZADOR_PK PRIMARY KEY,
NOME VARCHAR(100), 
CNPJ VARCHAR(14) UNIQUE, 
TELEFONE INT
)

CREATE TABLE TB_EVENTO(
CODIGO INT IDENTITY CONSTRAINT CONST_EVENTO_PK PRIMARY KEY,
NOME VARCHAR(100),
DATA DATE,
FK_LOCAL INT CONSTRAINT CONST_LOCAL_FK FOREIGN KEY REFERENCES TB_LOCAL(CODIGO),
FK_ORGANIZADOR INT CONSTRAINT CONST_ORGANIZADOR_FK FOREIGN KEY REFERENCES TB_ORGANIZADOR(MATRICULA)
)

CREATE TABLE TB_ESTILO_MUSICAL (
CODIGO INT IDENTITY CONSTRAINT CONST_ESTILOMUSIC_PK PRIMARY KEY,
NOME VARCHAR(100)
)

CREATE TABLE TB_ARTISTA (
CODIGO INT IDENTITY CONSTRAINT CONST_ARTISTA_PK PRIMARY KEY,
NOME VARCHAR(100),
CPF VARCHAR(11) UNIQUE,
FK_ESTILO_MUSICAL INT CONSTRAINT CONST_ESTILOMUSIC_FK FOREIGN KEY REFERENCES TB_ESTILO_MUSICAL(CODIGO)
)

CREATE TABLE TB_CACHE(
CODIGO INT IDENTITY CONSTRAINT CONST_CACHE_PK PRIMARY KEY,
VALOR MONEY,
DESCRICAO VARCHAR(100),
FK_ARTISTA INT CONSTRAINT CONST_ARTISTA_FK FOREIGN KEY REFERENCES TB_ARTISTA(CODIGO),
FK_EVENTO INT CONSTRAINT CONST_EVENTO_FK FOREIGN KEY REFERENCES TB_EVENTO(CODIGO)
)