CREATE DATABASE DB_FLORICULTURA

USE DB_FLORICULTURA

CREATE TABLE TB_CLIENTE(
CPF VARCHAR(11) CONSTRAINT CONST_PK_CLIENTE PRIMARY KEY,
NOME VARCHAR(100),
TELEFONE INT,
EMAIL VARCHAR(100),
CEP INT
)

CREATE TABLE TB_VENDEDOR(
MATRICULA INT IDENTITY CONSTRAINT CONST_PK_VENDEDOR PRIMARY KEY,
NOME VARCHAR(100),
CPF VARCHAR(11) CONSTRAINT CONST_UNIQUE_VENDEDOR UNIQUE,
CEP INT,
SALARIO SMALLMONEY
)

CREATE TABLE TB_PEDIDO(
CODIGO_NOTA INT IDENTITY CONSTRAINT CONST_PK_PEDIDO PRIMARY KEY,
DATA_PEDIDO DATE,
FK_CLIENTE VARCHAR(11) CONSTRAINT CONST_FK_CLIENTE_PED FOREIGN KEY REFERENCES TB_CLIENTE(CPF),
FK_VENDEDOR INT CONSTRAINT CONST_FK_VENDEDOR_PED FOREIGN KEY REFERENCES TB_VENDEDOR(MATRICULA)
)

CREATE TABLE TB_FORMA_PGTO(
SIGLA VARCHAR(3) CONSTRAINT CONST_PK_FORMAPGTO PRIMARY KEY,
DESCRICAO VARCHAR(100) 
)

CREATE TABLE TB_PEDIDO_PGTO(
CODIGO INT IDENTITY CONSTRAINT CONST_PEDPGTO_PK PRIMARY KEY,
FK_PEDIDO_PEDPGTO INT CONSTRAINT CONST_PEDIDO_PEDPGTO_FK FOREIGN KEY REFERENCES TB_PEDIDO(CODIGO_NOTA),
FK_FORMAPGTO_PEDPGTO VARCHAR(3) CONSTRAINT CONST_FORMAPGTO_PEDPGTO_FK FOREIGN KEY REFERENCES TB_FORMA_PGTO(SIGLA)
)

CREATE TABLE TB_PRODUTO(
CODIGO INT IDENTITY CONSTRAINT CONST_PRODUTO_PK PRIMARY KEY,
NOME VARCHAR(50),
PRECO SMALLMONEY,
QTD_ESTOQUE INT,
QTD_ITENS_VENDIDOS INT,
)

CREATE TABLE TB_PED_PRODUTO(
CODIGO INT IDENTITY CONSTRAINT CONST_PEDPROD_PK PRIMARY KEY,
FK_PROD_PEDPROD INT CONSTRAINT CONST_PROD_PEDPROD_FK FOREIGN KEY REFERENCES TB_PRODUTO(CODIGO),
FK_PED_PEDPROD INT CONSTRAINT CONST_PED_PEDPROD_FK FOREIGN KEY REFERENCES TB_PEDIDO(CODIGO_NOTA)
)

CREATE TABLE TB_CATEGORIA(
CODIGO INT IDENTITY CONSTRAINT CONST_CATEG_PK PRIMARY KEY,
FK_PROD_CATEG INT CONSTRAINT CONST_PROD_CATEG_FK FOREIGN KEY REFERENCES TB_PRODUTO(CODIGO)
)