CREATE DATABASE DB_LOCADORA_FILME

USE DB_LOCADORA_FILME

CREATE TABLE TB_NACIONALIDADE(
PAIS_ID VARCHAR(3) CONSTRAINT CONST_PK_NACIONALIDADE PRIMARY KEY,
NOME VARCHAR(50)
)

CREATE TABLE TB_CLIENTE(
CPF VARCHAR(11) CONSTRAINT CONST_PK_CLIENTE PRIMARY KEY,
NOME VARCHAR(100),
DATA_NASC DATE,
)

CREATE TABLE TB_CATEGORIA(
CODIGO INT IDENTITY CONSTRAINT CONST_PK_CATEGORIA PRIMARY KEY,
NOME VARCHAR(50)
)

CREATE TABLE TB_LOCACAO (
CODIGO INT IDENTITY CONSTRAINT CONST_PK_LOCACAO PRIMARY KEY,
FK_CLIENTE VARCHAR(11) CONSTRAINT CONST_FK_LOCACAO_CLIENTE FOREIGN KEY REFERENCES TB_CLIENTE(CPF)
)

CREATE TABLE TB_FILME (
ID INT CONSTRAINT CONST_PK_FILME PRIMARY KEY,
NOME VARCHAR(100),
DURACAO FLOAT,
FK_PAIS_FILME VARCHAR(3) CONSTRAINT FK_PAIS_FILME FOREIGN KEY REFERENCES TB_NACIONALIDADE(PAIS_ID),
FK_CATEGORIA_FILME INT CONSTRAINT FK_CATEG_FILME FOREIGN KEY REFERENCES TB_CATEGORIA(CODIGO) 
)

CREATE TABLE TB_MIDIA (
CODIGO INT CONSTRAINT CONST_PK_MIDIA PRIMARY KEY,
NOME VARCHAR(100),
QTD INT,
FK_FILME_MIDIA INT CONSTRAINT CONT_FK_FILME_MIDIA FOREIGN KEY REFERENCES TB_FILME(ID)
)

CREATE TABLE TB_LOC_MIDIA (
CODIGO INT CONSTRAINT CONST_PK_CODIGO PRIMARY KEY,
FK_LOCMID_LOCACAO INT CONSTRAINT CONST_FK_LOCMID_LOCACAO FOREIGN KEY REFERENCES TB_LOCACAO(CODIGO),
FK_LOCMID_MIDIA INT CONSTRAINT CONST_FK_LOCMID_MIDIA FOREIGN KEY REFERENCES TB_MIDIA(CODIGO)
)